### ISSUE TITLE
Error while re-training model 

### ISSUE THREAD

**Issue by gouravapplify** [googlecodelabs/tensorflow-for-poets-2#100]
Below are my terminal work:

**applify@appadmin-Vostro-15-3568:**~$ cd ~/Downloads/tensorflow
**applify@appadmin-Vostro-15-3568:**~/Downloads/tensorflow$ ls
android  CONTRIBUTING.md  ios  LICENSE  README.md  scripts  tf_files
**applify@appadmin-Vostro-15-3568:**~/Downloads/tensorflow$ ls tf_files/flower_photols: cannot access 'tf_files/flower_photo': No such file or directory
**applify@appadmin-Vostro-15-3568:**~/Downloads/tensorflow$ ls tf_files/flower_photos
daisy  dandelion  LICENSE.txt  roses  sunflowers  tulips
**applify@appadmin-Vostro-15-3568:**~/Downloads/tensorflow$ IMAGE_SIZE=224applify@appadmin-**Vostro-15-3568:**~/Downloads/tensorflow$ ARCHITECTURE="mobilenet_0.50_${IMAGE_SIZE}"
**applify@appadmin-Vostro-15-3568:**~/Downloads/tensorflow$ python -m scripts.retrain -h
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/applify/Downloads/tensorflow/scripts/retrain.py", line 108, in <module>
    import numpy as np
ImportError: No module named numpy
**applify@appadmin-Vostro-15-3568:**~/Downloads/tensorflow$

**Comment by bigsnarfdude** [comment]
ImportError: No module named numpy

**Comment by sushantag9** [comment]
Try "pip install numpy" in cmd
