### ISSUE TITLE
I have error when i try to retrain the data

### ISSUE THREAD

**Issue by George35mk** [googlecodelabs/tensorflow-for-poets-2#11]
```
PS C:\Users\George35mk\Desktop\MACHINE LERNING EXAMPLES\Google Developers\Train an Image Classifier with TensorFlow for Poets - Machine Learning Recipes #6\tensorflow-for-poets-2> python -m scripts.retrain --bottleneck_dir=tf_files/bottlenecks --how_many_training_steps=500 --model_dir=tf_files/models/  --summaries_dir=tf_files/training_summaries/"${ARCHITECTURE}" --output_graph=tf_files/retrained_graph.pb --output_labels=tf_files/retrained_labels.txt --architecture="${ARCHITECTURE}" --image_dir=tf_files/flower_photos
ERROR:tensorflow:Couldn't understand architecture name ''
Traceback (most recent call last):
  File "C:\Users\George35mk\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\George35mk\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\George35mk\Desktop\MACHINE LERNING EXAMPLES\Google Developers\Train an Image Classifier with TensorFlow for Poets - Machine Learning Recipes #6\tensorflow-for-poets-2\scripts\retrain.py", line 1257, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\George35mk\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:\Users\George35mk\Desktop\MACHINE LERNING EXAMPLES\Google Developers\Train an Image Classifier with TensorFlow for Poets - Machine Learning Recipes #6\tensorflow-for-poets-2\scripts\retrain.py", line 907, in main
    model_info = create_model_info(FLAGS.architecture)
  File "C:\Users\George35mk\Desktop\MACHINE LERNING EXAMPLES\Google Developers\Train an Image Classifier with TensorFlow for Poets - Machine Learning Recipes #6\tensorflow-for-poets-2\scripts\retrain.py", line 856, in create_model_info
    raise ValueError('Unknown architecture', architecture)
ValueError: ('Unknown architecture', '')
PS C:\Users\George35mk\Desktop\MACHINE LERNING EXAMPLES\Google Developers\Train an Image Classifier with TensorFlow for Poets - Machine Learning Recipes #6\tensorflow-for-poets-2>

```

**Comment by nemo-and-dory** [comment]
George, take another look at: https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#3

If you're on Windows, at the command prompt type "set" before entering the architecture and image size variables. Like:  >Set ARCHITECTURE="mobilenet_0.50_${IMAGE_SIZE}"

 Different than Linux. Hope that helps.

**Comment by George35mk** [comment]
Thanks, I have solved that by adding manual a string name

**Comment by saik4t** [comment]
Hey George, can you help me how did you manually solve it ?

**Comment by AasthaVarma** [comment]
Replace **"${ARCHITECTURE}"** with **"mobilenet_0.50_224"**

Code looks like this --- 
python -m scripts.retrain \
  --bottleneck_dir=tf_files/bottlenecks \
  --how_many_training_steps=500 \
  --model_dir=tf_files/models/ \
  --summaries_dir=tf_files/training_summaries/"mobilenet_0.50_224" \
  --output_graph=tf_files/retrained_graph.pb \
  --output_labels=tf_files/retrained_labels.txt \
  --architecture="mobilenet_0.50_224" \
  --image_dir=tf_files/flower_photos
