### ISSUE TITLE
retrain.py IOError: CRC check failed 

### ISSUE THREAD

**Issue by corlov** [googlecodelabs/tensorflow-for-poets-2#114]
Hi all!
I use tensorflow 1.11.0 and Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux.
I have tried to run retrain-script where I specified architecture parameter as inception_v3 and got an error message:

```
python scripts/retrain.py \
    --output_graph=tf_files/retrained_veh_graph_50_iv3.pb \
    --output_labels=tf_files/retrained_veh_labels_50_iv3.txt \
    --image_dir=tf_files/car_photos_50 \
    --architecture=inception_v3 \
    --summaries_dir tf_files/training_summaries_veh_50_iv3/inception_v3 \
    --how_many_training_steps 60000
```

Traceback (most recent call last):
  File "scripts/retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "scripts/retrain.py", line 982, in main
    maybe_download_and_extract(model_info['data_url'])
  File "scripts/retrain.py", line 340, in maybe_download_and_extract
    tarfile.open(filepath, 'r:gz').extractall(dest_directory)
  File "/usr/lib/python2.7/tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "/usr/lib/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib/python2.7/tarfile.py", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python2.7/tarfile.py", line 2235, in makefile
    copyfileobj(source, target)
  File "/usr/lib/python2.7/tarfile.py", line 266, in copyfileobj
    shutil.copyfileobj(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib/python2.7/tarfile.py", line 831, in read
    buf += self.fileobj.read(size - len(buf))
  File "/usr/lib/python2.7/tarfile.py", line 743, in read
    return self.readnormal(size)
  File "/usr/lib/python2.7/tarfile.py", line 758, in readnormal
    return self.__read(size)
  File "/usr/lib/python2.7/tarfile.py", line 748, in __read
    buf = self.fileobj.read(size)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
**IOError: CRC check failed 0x4c38fcc0 != 0xf3121d9L**

I have run the script with mobilenet_1.0_224 setting and it was executed successfully:

```
python scripts/retrain.py \
    --output_graph=tf_files/retrained_veh_graph_50.pb \
    --output_labels=tf_files/retrained_veh_labels_50.txt \
    --image_dir=tf_files/car_photos_50 \
    --architecture=mobilenet_1.0_224 \
    --summaries_dir tf_files/training_summaries_veh_50/mobilenet_1.0_244 \
    --how_many_training_steps 30000
```

**Comment by xiaoyangnihao** [comment]
@corlov hi, I met the same error, do you know how to solve this problem, help me out this problem, thanks

**Comment by corlov** [comment]
xiaoyangnihao hi. Unfortunately no. I use mobilenet_1.0_224 still in my task.
