### ISSUE TITLE
Optimize for inference - Mobile optimizing graph error.

### ISSUE THREAD

**Issue by MauryaRitesh** [googlecodelabs/tensorflow-for-poets-2#21]
I got the following error, while optimizing for mobile:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/riteshk_m_786/.local/lib/python3.6/site-packages/tensorflow/python/tools/optimize_for_inference.py", line 146, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/riteshk_m_786/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/riteshk_m_786/.local/lib/python3.6/site-packages/tensorflow/python/tools/optimize_for_inference.py", line 90, in main
    FLAGS.output_names.split(","), FLAGS.placeholder_type_enum)
  File "/home/riteshk_m_786/.local/lib/python3.6/site-packages/tensorflow/python/tools/optimize_for_inference_lib.py", line 109, in optimize_for_inference
    placeholder_type_enum)
  File "/home/riteshk_m_786/.local/lib/python3.6/site-packages/tensorflow/python/tools/strip_unused_lib.py", line 83, in strip_unused
    raise KeyError("The following input nodes were not found: %s\n" % not_found)
KeyError: "The following input nodes were not found: {'input'}\n"

**Comment by MauryaRitesh** [comment]
It was due to Python Version Mismatching. Mine machine had python3.6 and this code is written in python3.5.3, so make sure to take close look at the version system!

**Comment by BharathBillawa** [comment]
If you are using mobilenet the input node will be "input",
but in inception its "mul" . So just replace that ...
I think that'll work.. :)

**Comment by Sagarsharma4244** [comment]
If you are getting an error KeyError: "The following input nodes were not found: {'input'}\n" then change "input" to "Mul" 
If anybody still has doubt refer [https://medium.com/towards-data-science/tensorflow-on-mobile-tutorial-1-744703297267]
