### ISSUE TITLE
Run the customized app occur an error

### ISSUE THREAD

**Issue by DenisN03** [googlecodelabs/tensorflow-for-poets-2#25]
If you perform step 8, a modified application is started, an error occurs. I changed the name of the last layer as indicated in the instructions and copied the model and labels. But when I run the application on the phone an error occurs: 
01-11 13:48:00.124 18608-18608/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.tensorflow.demo, PID: 18608
                                                   java.lang.RuntimeException: Failed to load model from 'file:///android_asset/graph.pb'
                                                       at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:100)
                                                       at org.tensorflow.demo.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:103)
                                                       at org.tensorflow.demo.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:130)
                                                       at org.tensorflow.demo.CameraActivity$1.onPreviewSizeChosen(CameraActivity.java:159)
                                                       at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:421)
                                                       at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:428)
                                                       at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:64)
                                                       at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:95)
                                                       at android.view.TextureView.getHardwareLayer(TextureView.java:368)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15244)
                                                       at android.view.View.draw(View.java:16040)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15262)
                                                       at android.view.View.draw(View.java:16040)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                       at android.view.View.draw(View.java:16273)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15267)
                                                       at android.view.View.draw(View.java:16040)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15262)
                                                       at android.view.View.draw(View.java:16040)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15262)
                                                       at android.view.View.draw(View.java:16040)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                       at android.view.View.draw(View.java:16273)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2697)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15267)
                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2619)
                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2438)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2071)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1111)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6017)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:234)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: Mobi
01-11 13:50:09.979 18608-18608/org.tensorflow.demo I/Process: Sending signal. PID: 18608 SIG: 9

Does anyone know what this error is related to?

**Comment by bmabir17** [comment]
I am facing the same error log. Followed the solution here https://github.com/tensorflow/tensorflow/issues/15698
But the problems remains

**Comment by SalmonTimo** [comment]
I had this error a few hours ago.

The solution listed at [tensorflow/tensorflow#15698](https://github.com/tensorflow/tensorflow/issues/15698) specifies to change the build.gradle dependency to

`dependencies {
    compile 'org.tensorflow:tensorflow-android:+'
}`

or perhaps to replace the "+" above with 1.4.0.

You need to replace the "+" it to the particular tensorflow version that you used to retrain the custom network. For example, I used

`dependencies {
    compile 'org.tensorflow:tensorflow-android:1.5.0'
}`

because my tensorflow version is currently 1.5.0

**Comment by ElephantHunters** [comment]
if anyone faced the same problem,my step might help you.
as i was facing the same error,so what i did 
changed this line
dependencies { 
    compile 'org.tensorflow:tensorflow-android:1.2.0-preview' 
}
to 
dependencies { 
    compile 'org.tensorflow:tensorflow-android:1.6.0' 
}
since i'm using tensorflow 1.6.0
then i was getting deprecated warning about compile ,so therefore i changed it to "implementation"
therefore now it look like this 

dependencies { 
    implementation 'org.tensorflow:tensorflow-android:1.6.0' 
}
but then as soon i run my app i faced another problem which was 
"Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebug'. > com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex"

so,what i did i went to build options ,choose clean project ,then after cleaning was performed by Android Studio,
i clicked on rebuild project,

then i clicked on run, and then app started running fine with no crashing 

i hope it helps ,anyone who faced the problem like me,here the proof of my result
![image](https://user-images.githubusercontent.com/26957301/37251446-237f0c52-2536-11e8-9ee2-21a6d0cc26e5.png)

**Comment by GajjarMihir** [comment]
@ElephantHunters your solution did work. Thanks :)

**Comment by GeneratorEX** [comment]
@ElephantHunters after changing the build.gradle dependencies I encountered another error


Unable to solve dependency for 'app@debugAndroidTest/compileClasspath' Could not resolve org.tensorflow:tensorflow-androidl:1.9.0.

**Comment by xiongxiongge08** [comment]
> I am facing the same error log. Followed the solution here [tensorflow/tensorflow#15698](https://github.com/tensorflow/tensorflow/issues/15698)
> But the problems remains
> 
> Update: It was mainly due to the android library not supporting models trained with tensorflow 1.5. The only solution was to retrain the model using tensorflow 1.4

I have tried tons of solutions but only your answer works for me. Thank you so much!
