### ISSUE TITLE
Accidentally cancelled inceptionV3 while downloading, now unable to download

### ISSUE THREAD

**Issue by sudopower** [googlecodelabs/tensorflow-for-poets-2#65]
The Error
> tf>python3 -m scripts.retrain \
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Kiran\Projects\ImageRecog\tf\scripts\retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "D:\Kiran\Projects\ImageRecog\tf\scripts\retrain.py", line 982, in main
    maybe_download_and_extract(model_info['data_url'])
  File "D:\Kiran\Projects\ImageRecog\tf\scripts\retrain.py", line 340, in maybe_download_and_extract
    tarfile.open(filepath, 'r:gz').extractall(dest_directory)
  File "C:\Program Files\Python36\lib\tarfile.py", line 2008, in extractall
    numeric_owner=numeric_owner)
  File "C:\Program Files\Python36\lib\tarfile.py", line 2050, in extract
    numeric_owner=numeric_owner)
  File "C:\Program Files\Python36\lib\tarfile.py", line 2120, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Program Files\Python36\lib\tarfile.py", line 2169, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "C:\Program Files\Python36\lib\tarfile.py", line 249, in copyfileobj
    buf = src.read(bufsize)
  File "C:\Program Files\Python36\lib\gzip.py", line 276, in read
    return self._buffer.read(size)
  File "C:\Program Files\Python36\lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "C:\Program Files\Python36\lib\gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

**Comment by blockhunts** [comment]
try to delete all files that has been made when you run the command.

**Comment by Sagarsharma4244** [comment]
try to run  the same retrain command with adding this argument `--architecture mobilenet_1.0_224` 
This will download a different faster smaller model other than Inception

**Comment by sudopower** [comment]
But I need Inception, I have, one trained using mobilenet

**Comment by sushantag9** [comment]
The files created in the model folder, delete them and then try again

**Comment by sudopower** [comment]
I tried all the above solutions, unfortunately I was running out of time and decided to do it all over again inside of a VM, will try to fix it and open another issue later. Thank you !
